server:
  servlet:
    context-path: /api/v1

logging:
  file:
    name: logs/app.log
  level:
    root: INFO

spring:
  application:
    name: movies-api

  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: ${MONGO_URI}
